### ISSUE TITLE
ОКПО 20557396 не валидируется

### ISSUE THREAD

**Issue by rimmer333** [asiniy/validates_russian#18]
Это валидный реальный ОКПО реальной компании, но валидатор okpo_format: true не пропускает такое значение

**Comment by asiniy** [comment]
ок. Изучите валидатор, поймите, почему не валидируется, и отправьте pull request

**Comment by AgeevAndrew** [comment]
Пулреквест давным давно ожидает https://github.com/asiniy/validates_russian/pull/17
